// Nakshatra-specific remedies based on classical Vedic texts
// Sources: BPHS Ch. 84-96, Saravali Ch. 32, Horasara Ch. 2, Brihat Jataka Ch. 16
// Maps to ClickAstro Chapter 9: "Remedies Based on Your Birth Star"

export interface NakshatraRemedy {
  nakshatra: string;
  starLord: string;
  signLord: string;
  sign: string;
  element: string;
  animal: string;
  tree: string;
  bird: string;
  guna: 'Sattva' | 'Rajas' | 'Tamas';
  motivation: 'Dharma' | 'Artha' | 'Kama' | 'Moksha';
  gender: 'Male' | 'Female';
  caste: 'Brahmin' | 'Kshatriya' | 'Vaishya' | 'Shudra';
  bodyPart: string;
  hostileDasas: string[];
  hostileNakshatras: string[];
  characteristics: string;
  generalAdvice: string;
  remedies: {
    prayer: string;
    fasting: string;
    dress: string;
    deity: string;
    mantras: string[];
    nurturing: string;
  };
}

export const nakshatraRemedies: Record<string, NakshatraRemedy> = {
  'Ashwini': {
    nakshatra: 'Ashwini',
    starLord: 'Ketu',
    signLord: 'Mars',
    sign: 'Aries',
    element: 'Earth',
    animal: 'Horse',
    tree: 'Nux Vomica (Strychnine tree)',
    bird: 'Wild Eagle',
    guna: 'Sattva',
    motivation: 'Dharma',
    gender: 'Male',
    caste: 'Vaishya',
    bodyPart: 'Upper feet',
    hostileDasas: ['Saturn', 'Rahu', 'Mercury'],
    hostileNakshatras: ['Jyeshtha', 'Ashlesha', 'Magha'],
    characteristics: 'As you are born in the Ashwini star, your star lord is Ketu. You are naturally energetic, quick in action, and have a healing touch. Your pioneering spirit drives you to initiate new ventures. However, impatience and restlessness during unfavorable periods may create obstacles in achieving your aims.',
    generalAdvice: 'Practice patience and restraint during unfavorable dasa periods. Avoid hasty decisions, especially in financial matters. Maintain good health practices and stay grounded through regular routines.',
    remedies: {
      prayer: 'Pray to Ashwini Kumaras and the lords of Ketu regularly, particularly during hostile dasa periods. Observing fast on Tuesdays and visiting temples of Lord Ganesha will give excellent results.',
      fasting: 'Observe fasting on Tuesdays and on days when Ashwini nakshatra falls',
      dress: 'Wear red, saffron, and earthy tones to please Mars, the sign lord. Wearing these colors on Tuesdays is especially beneficial.',
      deity: 'Ashwini Kumaras are the divine physicians. Worship Lord Ganesha for removing obstacles.',
      mantras: ['Om Ashwini Kumarabhyam Namah', 'Om Ketve Namah'],
      nurturing: 'Caring for horses and equine animals is considered highly auspicious. Do not harm the Strychnine tree. Among the five elements, Earth is the element of Ashwini. Respecting and protecting the earth brings good fortune.',
    },
  },
  'Bharani': {
    nakshatra: 'Bharani',
    starLord: 'Venus',
    signLord: 'Mars',
    sign: 'Aries',
    element: 'Water',
    animal: 'Elephant',
    tree: 'Amla (Indian Gooseberry)',
    bird: 'Crow',
    guna: 'Rajas',
    motivation: 'Artha',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Head',
    hostileDasas: ['Saturn', 'Rahu', 'Ketu'],
    hostileNakshatras: ['Mula', 'Purva Bhadrapada', 'Magha'],
    characteristics: 'Born in Bharani, your star lord is Venus. You possess strong creative abilities and a sense of justice. You may be drawn to transformative experiences. During unfavorable periods, you may face challenges related to finances and relationships.',
    generalAdvice: 'Maintain virtue and discipline during unfavorable periods. Avoid overindulgence in sensual pleasures. Practice moderation in all aspects of life.',
    remedies: {
      prayer: 'Pray to Lord Yama for righteous living and to Venus for prosperity. Visit temples on Fridays and offer white flowers.',
      fasting: 'Observe fasting on Fridays and on days when Bharani nakshatra falls',
      dress: 'Wear white, cream, and light blue colors to please Venus. Fridays are especially favorable for bright attire.',
      deity: 'Yama, the lord of Dharma, is the presiding deity. Worship Mahalakshmi for prosperity.',
      mantras: ['Om Yamaaya Namah', 'Om Shukraaya Namah'],
      nurturing: 'Caring for elephants and large animals brings good fortune. Plant and protect Amla trees. Water element activities like visiting sacred rivers are beneficial.',
    },
  },
  'Krittika': {
    nakshatra: 'Krittika',
    starLord: 'Sun',
    signLord: 'Mars/Venus',
    sign: 'Aries/Taurus',
    element: 'Fire',
    animal: 'Goat',
    tree: 'Fig Tree (Cluster Fig)',
    bird: 'Peacock',
    guna: 'Rajas',
    motivation: 'Kama',
    gender: 'Female',
    caste: 'Brahmin',
    bodyPart: 'Head, eyes',
    hostileDasas: ['Saturn', 'Rahu', 'Venus'],
    hostileNakshatras: ['Vishakha', 'Anuradha', 'Purva Ashadha'],
    characteristics: 'Born in Krittika, your star lord is Sun. You are determined, sharp, and have a purifying influence on those around you. You possess fame-bringing qualities. However, sharp speech during unfavorable times may create enemies.',
    generalAdvice: 'Control your speech and temper during challenging periods. Channel your fire energy into constructive pursuits. Practice diplomacy and patience in dealings.',
    remedies: {
      prayer: 'Pray to Lord Agni and Sun God regularly. Offer water to the Sun at sunrise. Visit Shiva temples on Sundays.',
      fasting: 'Observe fasting on Sundays and on days when Krittika nakshatra falls',
      dress: 'Wear red, orange, and saffron colors to please the Sun. White is also auspicious due to the Taurus connection.',
      deity: 'Agni (Fire God) is the presiding deity. Worship Lord Kartikeya (Murugan) for protection.',
      mantras: ['Om Agnaye Namah', 'Om Suryaaya Namah'],
      nurturing: 'Caring for goats and fire-related service (lighting lamps in temples) is highly auspicious. Protect fig trees. Fire element rituals like Homa bring great benefits.',
    },
  },
  'Rohini': {
    nakshatra: 'Rohini',
    starLord: 'Moon',
    signLord: 'Venus',
    sign: 'Taurus',
    element: 'Earth',
    animal: 'Serpent',
    tree: 'Jamun (Java Plum)',
    bird: 'Owl',
    guna: 'Rajas',
    motivation: 'Moksha',
    gender: 'Male',
    caste: 'Shudra',
    bodyPart: 'Forehead, eyes',
    hostileDasas: ['Rahu', 'Saturn', 'Ketu'],
    hostileNakshatras: ['Ardra', 'Pushya', 'Magha', 'Mula', 'Purva Ashadha', 'Uttara Ashadha'],
    characteristics: 'As you are born in the Rohini star, your star lord is Moon. You like to talk pleasingly and interestingly. But the failure to consider the practical side of things in critical situations may be an obstacle in achieving your aims. On the basis of the birth star, the dasa periods of Rahu, Saturn and Ketu may be generally unfavorable to you.',
    generalAdvice: 'There will be visible changes in your words and actions during unfavorable periods. You may make changes in communication to maintain justice, but must not be short tempered. Avoid unnecessary transactions and auspicious functions on hostile stars.',
    remedies: {
      prayer: 'Pray regularly to Moon and the lords of Moon, particularly during hostile dasa periods. Observe fast on Amavasi days and on days when Mondays and Rohini star come together. Visit temples of Mother Goddess.',
      fasting: 'Observe fasting on Amavasi days and when Mondays coincide with Rohini nakshatra',
      dress: 'Select and wear white and sandalwood colored dresses to please Moon. Measures to please Venus, the lord of the sign, will also be beneficial.',
      deity: 'Lord Brahma is the lord of Rohini star. Also worship Mother Goddess and Lord Vishnu.',
      mantras: ['Om Brahmaaya Namah', 'Om Chandraaya Namah', 'Om Brahmane Namah'],
      nurturing: 'Nurturing plants, animals and birds is highly auspicious. Especially caring for serpents and not ill-treating them brings good fortune. Take care not to cut the Jamun tree. Among the five elements, Earth is the element of Rohini.',
    },
  },
  'Mrigashira': {
    nakshatra: 'Mrigashira',
    starLord: 'Mars',
    signLord: 'Venus/Mercury',
    sign: 'Taurus/Gemini',
    element: 'Earth',
    animal: 'Serpent',
    tree: 'Khadira (Acacia Catechu)',
    bird: 'Hen',
    guna: 'Tamas',
    motivation: 'Moksha',
    gender: 'Female',
    caste: 'Vaishya',
    bodyPart: 'Eyes, eyebrows',
    hostileDasas: ['Saturn', 'Rahu', 'Mercury'],
    hostileNakshatras: ['Ashlesha', 'Magha', 'Mula'],
    characteristics: 'Born in Mrigashira, your star lord is Mars. You possess a curious and searching nature with gentle manners. You have a keen eye for beauty and aesthetics. Restlessness and indecision during unfavorable periods may hinder progress.',
    generalAdvice: 'Focus your energy and avoid scattered pursuits during challenging periods. Maintain discipline and follow through on commitments. Regular exercise helps channel Mars energy constructively.',
    remedies: {
      prayer: 'Pray to Soma (Moon God) and Lord Kartikeya regularly. Visit temples on Tuesdays and offer red flowers.',
      fasting: 'Observe fasting on Tuesdays and on days when Mrigashira nakshatra falls',
      dress: 'Wear red, coral, and earthy tones to please Mars. Light colors also suit the gentle nature of this star.',
      deity: 'Soma (Moon) is the presiding deity. Worship Lord Subramanya for courage and focus.',
      mantras: ['Om Somaaya Namah', 'Om Mangalaaya Namah'],
      nurturing: 'Caring for deer and gentle animals brings good fortune. Protect Acacia trees. Earth-related activities like gardening are highly beneficial.',
    },
  },
  'Ardra': {
    nakshatra: 'Ardra',
    starLord: 'Rahu',
    signLord: 'Mercury',
    sign: 'Gemini',
    element: 'Water',
    animal: 'Dog',
    tree: 'Long Pepper',
    bird: 'Black Andril',
    guna: 'Tamas',
    motivation: 'Kama',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Eyes',
    hostileDasas: ['Sun', 'Mars', 'Ketu'],
    hostileNakshatras: ['Purva Phalguni', 'Uttara Phalguni', 'Vishakha'],
    characteristics: 'Born in Ardra, your star lord is Rahu. You possess intense transformative energy and sharp intelligence. You may experience sudden changes and upheavals. During unfavorable periods, emotional turbulence and health issues may arise.',
    generalAdvice: 'Practice emotional stability and avoid impulsive reactions during challenging times. Meditation and yoga help calm the intense energy of Rahu. Maintain honest dealings and avoid shortcuts.',
    remedies: {
      prayer: 'Pray to Lord Rudra (Shiva) and perform Rudra Abhisheka. Visit Shiva temples on Saturdays. Offer blue flowers and sesame oil lamps.',
      fasting: 'Observe fasting on Saturdays and on days when Ardra nakshatra falls',
      dress: 'Wear dark blue, black, and grey to please Rahu. Avoid very bright colors during hostile periods.',
      deity: 'Rudra (Lord Shiva in his fierce form) is the presiding deity. Worship Durga for protection.',
      mantras: ['Om Rudraaya Namah', 'Om Rahave Namah'],
      nurturing: 'Caring for dogs brings good fortune. Plant and protect pepper plants. Water element activities and visiting sacred water bodies are beneficial.',
    },
  },
  'Punarvasu': {
    nakshatra: 'Punarvasu',
    starLord: 'Jupiter',
    signLord: 'Mercury/Moon',
    sign: 'Gemini/Cancer',
    element: 'Water',
    animal: 'Cat',
    tree: 'Bamboo',
    bird: 'Swan',
    guna: 'Sattva',
    motivation: 'Artha',
    gender: 'Male',
    caste: 'Vaishya',
    bodyPart: 'Ears, nose',
    hostileDasas: ['Mercury', 'Venus', 'Saturn'],
    hostileNakshatras: ['Ashlesha', 'Chitra', 'Purva Ashadha'],
    characteristics: 'Born in Punarvasu, your star lord is Jupiter. You have a naturally optimistic and resilient nature with the ability to bounce back from setbacks. You are wise and spiritually inclined. During unfavorable periods, overconfidence may lead to poor judgments.',
    generalAdvice: 'Stay grounded and avoid overexpansion during challenging periods. Verify facts before making important decisions. Maintain spiritual practices for continued blessings.',
    remedies: {
      prayer: 'Pray to Mother Aditi and Lord Vishnu. Visit temples on Thursdays and offer yellow flowers. Perform charitable donations on Jupiter-related days.',
      fasting: 'Observe fasting on Thursdays and on days when Punarvasu nakshatra falls',
      dress: 'Wear yellow, golden, and light green colors to please Jupiter. Thursday is the best day for these colors.',
      deity: 'Aditi (Mother of the Gods) is the presiding deity. Worship Lord Rama for righteousness.',
      mantras: ['Om Aditye Namah', 'Om Gurave Namah'],
      nurturing: 'Caring for cats and feeding birds, especially swans, brings good fortune. Plant and protect bamboo. Water-related charity is highly auspicious.',
    },
  },
  'Pushya': {
    nakshatra: 'Pushya',
    starLord: 'Saturn',
    signLord: 'Moon',
    sign: 'Cancer',
    element: 'Water',
    animal: 'Goat',
    tree: 'Pipal (Sacred Fig)',
    bird: 'Sea Crow',
    guna: 'Tamas',
    motivation: 'Dharma',
    gender: 'Male',
    caste: 'Kshatriya',
    bodyPart: 'Mouth, face',
    hostileDasas: ['Sun', 'Mars', 'Rahu'],
    hostileNakshatras: ['Magha', 'Swati', 'Purva Bhadrapada'],
    characteristics: 'Born in Pushya, the most auspicious nakshatra, your star lord is Saturn. You have nurturing, protective qualities with a strong sense of duty. You are practical and responsible. During unfavorable periods, excessive worry and health issues may arise.',
    generalAdvice: 'Do not take on excessive responsibilities during hostile periods. Practice self-care alongside caring for others. Avoid unnecessary worry and maintain faith in divine timing.',
    remedies: {
      prayer: 'Pray to Brihaspati (Jupiter) and Lord Shiva. Visit temples on Saturdays wearing blue or black. Offer sesame oil lamps to Shani.',
      fasting: 'Observe fasting on Saturdays and on days when Pushya nakshatra falls',
      dress: 'Wear dark blue, black, and grey to please Saturn. White and silver also suit this nurturing star.',
      deity: 'Brihaspati (Jupiter, the divine teacher) is the presiding deity. Worship Lord Shiva and Hanuman.',
      mantras: ['Om Brihaspataye Namah', 'Om Shanaishcharaya Namah'],
      nurturing: 'Caring for cows and goats brings tremendous fortune. Water the Pipal tree and circumambulate it. Water-related charity and feeding the poor are highly meritorious.',
    },
  },
  'Ashlesha': {
    nakshatra: 'Ashlesha',
    starLord: 'Mercury',
    signLord: 'Moon',
    sign: 'Cancer',
    element: 'Water',
    animal: 'Cat',
    tree: 'Naga Champa',
    bird: 'Small Blue Sparrow',
    guna: 'Sattva',
    motivation: 'Dharma',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Ears',
    hostileDasas: ['Jupiter', 'Mars', 'Ketu'],
    hostileNakshatras: ['Mrigashira', 'Swati', 'Dhanishta'],
    characteristics: 'Born in Ashlesha, your star lord is Mercury. You possess deep wisdom, mystical abilities, and sharp intellect. You may have an interest in occult sciences. During unfavorable periods, suspicion and manipulation tendencies may surface.',
    generalAdvice: 'Practice transparency and honest communication during challenging periods. Channel your kundalini energy through meditation and yoga. Avoid secret dealings and maintain trust in relationships.',
    remedies: {
      prayer: 'Pray to Naga Devatas (Serpent Gods) and Lord Vishnu. Visit Naga temples and offer milk to serpent idols, especially on Naga Panchami.',
      fasting: 'Observe fasting on Wednesdays and on Naga Panchami days',
      dress: 'Wear green, light blue, and emerald tones to please Mercury. White is also auspicious due to the Cancer connection.',
      deity: 'Nagas (Divine Serpents) are the presiding deity. Worship Lord Subramanya and Naga Devata.',
      mantras: ['Om Sarpebhyo Namah', 'Om Budhaya Namah'],
      nurturing: 'Feeding and caring for cats brings good fortune. Never harm serpents. Plant Naga Champa trees. Water-related rituals and charity bring excellent results.',
    },
  },
  'Magha': {
    nakshatra: 'Magha',
    starLord: 'Ketu',
    signLord: 'Sun',
    sign: 'Leo',
    element: 'Water',
    animal: 'Rat',
    tree: 'Banyan',
    bird: 'Male Eagle',
    guna: 'Tamas',
    motivation: 'Artha',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Nose, lips',
    hostileDasas: ['Mercury', 'Rahu', 'Saturn'],
    hostileNakshatras: ['Ashwini', 'Chitra', 'Dhanishta'],
    characteristics: 'Born in Magha, your star lord is Ketu. You possess royal bearing, authority, and deep connection to ancestral lineage. You are naturally inclined toward leadership and tradition. During unfavorable periods, pride and ancestral karmic issues may surface.',
    generalAdvice: 'Honor your ancestors regularly through Pitru Tarpana. Maintain humility despite your natural authority. During hostile periods, avoid power struggles and ego conflicts.',
    remedies: {
      prayer: 'Pray to Pitris (Ancestors) and perform Pitru Tarpana regularly. Visit ancestral temples and offer Til (sesame) and water to departed souls, especially during Pitru Paksha.',
      fasting: 'Observe fasting during Pitru Paksha and on days when Magha nakshatra falls',
      dress: 'Wear golden, saffron, and royal colors to honor the Sun. Red and orange are also auspicious.',
      deity: 'Pitris (Divine Ancestors) are the presiding deities. Worship Lord Ganesha and perform ancestor rituals.',
      mantras: ['Om Pitribhyo Namah', 'Om Ketve Namah'],
      nurturing: 'Caring for rats and small animals brings ancestral blessings. Protect Banyan trees and circumambulate them. Water offerings to ancestors are highly meritorious.',
    },
  },
  'Purva Phalguni': {
    nakshatra: 'Purva Phalguni',
    starLord: 'Venus',
    signLord: 'Sun',
    sign: 'Leo',
    element: 'Water',
    animal: 'Rat',
    tree: 'Palash (Flame of the Forest)',
    bird: 'Female Eagle',
    guna: 'Tamas',
    motivation: 'Kama',
    gender: 'Female',
    caste: 'Brahmin',
    bodyPart: 'Right hand',
    hostileDasas: ['Saturn', 'Rahu', 'Ketu'],
    hostileNakshatras: ['Ardra', 'Anuradha', 'Shatabhisha'],
    characteristics: 'Born in Purva Phalguni, your star lord is Venus. You are naturally creative, sociable, and drawn to beauty and luxury. You enjoy pleasures and have artistic talents. During unfavorable periods, overindulgence and vanity may create problems.',
    generalAdvice: 'Practice moderation during challenging periods. Channel creative energy into productive pursuits. Maintain financial discipline and avoid extravagance.',
    remedies: {
      prayer: 'Pray to Lord Bhaga (God of Fortune) and Mahalakshmi. Visit temples on Fridays and offer white lotus flowers.',
      fasting: 'Observe fasting on Fridays and on days when Purva Phalguni falls',
      dress: 'Wear white, cream, and light pink to please Venus. Silver jewelry is also auspicious.',
      deity: 'Bhaga (God of Marital Bliss and Fortune) is the presiding deity. Worship Lakshmi for prosperity.',
      mantras: ['Om Bhagaaya Namah', 'Om Shukraaya Namah'],
      nurturing: 'Caring for birds and maintaining gardens brings fortune. Protect Palash trees. Water-related charity and supporting marriage functions are meritorious.',
    },
  },
  'Uttara Phalguni': {
    nakshatra: 'Uttara Phalguni',
    starLord: 'Sun',
    signLord: 'Sun/Mercury',
    sign: 'Leo/Virgo',
    element: 'Fire',
    animal: 'Bull',
    tree: 'Rose Laurel',
    bird: 'Beetle',
    guna: 'Rajas',
    motivation: 'Moksha',
    gender: 'Female',
    caste: 'Kshatriya',
    bodyPart: 'Left hand',
    hostileDasas: ['Saturn', 'Rahu', 'Ketu'],
    hostileNakshatras: ['Ardra', 'Anuradha', 'Shatabhisha'],
    characteristics: 'Born in Uttara Phalguni, your star lord is Sun. You are generous, friendly, and skilled in forming lasting partnerships. You have leadership abilities combined with a service-oriented nature. During unfavorable periods, you may face issues with contracts and partnerships.',
    generalAdvice: 'Be careful with agreements and partnerships during hostile periods. Maintain your generous nature but set boundaries. Practice Sun worship for continued strength.',
    remedies: {
      prayer: 'Pray to Aryaman (God of Contracts and Friendship) and Sun God. Offer water to the Sun at sunrise daily. Visit Sun temples on Sundays.',
      fasting: 'Observe fasting on Sundays and on days when Uttara Phalguni falls',
      dress: 'Wear golden, orange, and saffron to honor the Sun. Ruby-colored attire is also auspicious.',
      deity: 'Aryaman (God of Contracts) is the presiding deity. Worship Surya (Sun God) for vitality.',
      mantras: ['Om Aryamne Namah', 'Om Suryaaya Namah'],
      nurturing: 'Caring for bulls and cattle brings good fortune. Protect Rose Laurel plants. Fire rituals (Homa/Havan) are highly beneficial.',
    },
  },
  'Hasta': {
    nakshatra: 'Hasta',
    starLord: 'Moon',
    signLord: 'Mercury',
    sign: 'Virgo',
    element: 'Fire',
    animal: 'Buffalo',
    tree: 'Hog Plum',
    bird: 'Vulture',
    guna: 'Rajas',
    motivation: 'Moksha',
    gender: 'Male',
    caste: 'Vaishya',
    bodyPart: 'Fingers',
    hostileDasas: ['Rahu', 'Saturn', 'Ketu'],
    hostileNakshatras: ['Mula', 'Purva Bhadrapada', 'Ashwini'],
    characteristics: 'Born in Hasta, your star lord is Moon. You possess exceptional manual dexterity, healing abilities, and skill in crafts. You are clever, resourceful, and adaptable. During unfavorable periods, emotional instability and cunning tendencies may arise.',
    generalAdvice: 'Use your skills constructively during challenging times. Avoid manipulative behavior. Practice emotional regulation through meditation and creative activities.',
    remedies: {
      prayer: 'Pray to Savitar (Sun God in creative aspect) and Moon God. Visit temples on Mondays and offer white flowers. Perform charitable healing activities.',
      fasting: 'Observe fasting on Mondays and on days when Hasta nakshatra falls',
      dress: 'Wear white, cream, and silver colors to please Moon. Light green is also suitable for Mercury connection.',
      deity: 'Savitar (the vivifying form of Sun) is the presiding deity. Worship Lord Vishnu for sustenance.',
      mantras: ['Om Savitre Namah', 'Om Chandraaya Namah'],
      nurturing: 'Caring for buffalo and domesticated animals brings fortune. Practice handicrafts and donate handmade items. Fire rituals bring excellent results.',
    },
  },
  'Chitra': {
    nakshatra: 'Chitra',
    starLord: 'Mars',
    signLord: 'Mercury/Venus',
    sign: 'Virgo/Libra',
    element: 'Fire',
    animal: 'Tiger',
    tree: 'Bilva (Wood Apple)',
    bird: 'Woodpecker',
    guna: 'Tamas',
    motivation: 'Kama',
    gender: 'Female',
    caste: 'Vaishya',
    bodyPart: 'Neck',
    hostileDasas: ['Saturn', 'Rahu', 'Mercury'],
    hostileNakshatras: ['Magha', 'Dhanishta', 'Ashwini'],
    characteristics: 'Born in Chitra, your star lord is Mars. You are naturally creative, beautiful, and have an eye for architecture and design. You possess artistic talents and charisma. During unfavorable periods, vanity and impulsive spending may create difficulties.',
    generalAdvice: 'Channel creative energy into structured projects during challenging times. Avoid impulsive purchases and maintain financial discipline. Exercise regularly to burn Mars energy constructively.',
    remedies: {
      prayer: 'Pray to Tvashtar (Celestial Architect) and Lord Vishwakarma. Visit temples on Tuesdays and offer red flowers. Perform creative arts as worship.',
      fasting: 'Observe fasting on Tuesdays and on days when Chitra nakshatra falls',
      dress: 'Wear red, coral, and bright colors to please Mars. Creative and artistic attire suits this star.',
      deity: 'Tvashtar (Celestial Architect/Creator) is the presiding deity. Worship Lord Vishwakarma for skill.',
      mantras: ['Om Tvashtre Namah', 'Om Mangalaaya Namah'],
      nurturing: 'Protecting tigers and wild cats brings good fortune. Plant Bilva trees near Shiva temples. Fire-related activities and artistic creation are highly beneficial.',
    },
  },
  'Swati': {
    nakshatra: 'Swati',
    starLord: 'Rahu',
    signLord: 'Venus',
    sign: 'Libra',
    element: 'Fire',
    animal: 'Buffalo',
    tree: 'Arjuna Tree',
    bird: 'Honey Bee',
    guna: 'Tamas',
    motivation: 'Artha',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Chest',
    hostileDasas: ['Sun', 'Mars', 'Ketu'],
    hostileNakshatras: ['Ashlesha', 'Mrigashira', 'Purva Phalguni'],
    characteristics: 'Born in Swati, your star lord is Rahu. You are independent, flexible, and business-minded with a love for freedom. You adapt well to changing circumstances. During unfavorable periods, instability and scattered energy may hinder progress.',
    generalAdvice: 'Stay focused and committed during challenging periods. Avoid scattered pursuits and maintain a steady course. Practice grounding exercises and meditation to balance Rahu energy.',
    remedies: {
      prayer: 'Pray to Vayu (Wind God) and Lord Hanuman. Visit Hanuman temples on Saturdays and Tuesdays. Offer blue flowers and sesame oil lamps.',
      fasting: 'Observe fasting on Saturdays and on days when Swati nakshatra falls',
      dress: 'Wear dark blue, black, and multicolored attire to please Rahu. White also suits the Libra connection.',
      deity: 'Vayu (Wind God) is the presiding deity. Worship Lord Hanuman for strength and stability.',
      mantras: ['Om Vaayave Namah', 'Om Rahave Namah'],
      nurturing: 'Caring for buffalo and feeding birds brings fortune. Protect Arjuna trees. Fire element rituals and pranayama (breath work) are highly beneficial.',
    },
  },
  'Vishakha': {
    nakshatra: 'Vishakha',
    starLord: 'Jupiter',
    signLord: 'Venus/Mars',
    sign: 'Libra/Scorpio',
    element: 'Fire',
    animal: 'Tiger',
    tree: 'Wood Apple (Vilva)',
    bird: 'Sparrow Hawk',
    guna: 'Sattva',
    motivation: 'Dharma',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Arms',
    hostileDasas: ['Mercury', 'Venus', 'Saturn'],
    hostileNakshatras: ['Krittika', 'Uttara Phalguni', 'Uttara Ashadha'],
    characteristics: 'Born in Vishakha, your star lord is Jupiter. You are determined, goal-oriented, and have strong leadership abilities. You possess excellent oratory skills. During unfavorable periods, obsessiveness and jealousy may surface.',
    generalAdvice: 'Maintain ethical standards and avoid obsessive pursuit of goals during hostile periods. Practice gratitude and contentment. Share your success and wisdom generously.',
    remedies: {
      prayer: 'Pray to Indra-Agni and Lord Vishnu. Visit temples on Thursdays and offer yellow flowers. Perform charitable donations to educational institutions.',
      fasting: 'Observe fasting on Thursdays and on days when Vishakha nakshatra falls',
      dress: 'Wear yellow, golden, and saffron to please Jupiter. White and cream are also auspicious.',
      deity: 'Indra and Agni together are the presiding deities. Worship Lord Kartikeya and Goddess Lakshmi.',
      mantras: ['Om Indraagnibhyaam Namah', 'Om Gurave Namah'],
      nurturing: 'Protecting wild cats and offering food to spiritual seekers brings fortune. Plant and protect Wood Apple trees near temples. Fire rituals (Agnihotra) are highly meritorious.',
    },
  },
  'Anuradha': {
    nakshatra: 'Anuradha',
    starLord: 'Saturn',
    signLord: 'Mars',
    sign: 'Scorpio',
    element: 'Fire',
    animal: 'Deer',
    tree: 'Bakula (Maulsari)',
    bird: 'Nightingale',
    guna: 'Sattva',
    motivation: 'Dharma',
    gender: 'Male',
    caste: 'Shudra',
    bodyPart: 'Chest, stomach',
    hostileDasas: ['Sun', 'Mars', 'Rahu'],
    hostileNakshatras: ['Krittika', 'Purva Phalguni', 'Purva Ashadha'],
    characteristics: 'Born in Anuradha, your star lord is Saturn. You are devoted, friendly, and succeed in foreign lands. You have deep loyalty and organizational skills. During unfavorable periods, isolation and emotional hardship may arise.',
    generalAdvice: 'Maintain friendships and social connections during challenging periods. Avoid isolation and seek support from trusted friends. Practice devotion and spiritual disciplines regularly.',
    remedies: {
      prayer: 'Pray to Mitra (Sun God in friendly aspect) and Lord Shiva. Visit Shiva temples on Saturdays wearing dark blue. Offer sesame oil lamps.',
      fasting: 'Observe fasting on Saturdays and on days when Anuradha nakshatra falls',
      dress: 'Wear dark blue, black, and maroon to please Saturn. Red tones also suit the Scorpio connection.',
      deity: 'Mitra (God of Friendship and Alliances) is the presiding deity. Worship Lord Shiva and Vishnu.',
      mantras: ['Om Mitraaya Namah', 'Om Shanaishcharaya Namah'],
      nurturing: 'Caring for deer and graceful animals brings fortune. Protect Bakula trees. Fire element activities and lighting lamps in temples are highly beneficial.',
    },
  },
  'Jyeshtha': {
    nakshatra: 'Jyeshtha',
    starLord: 'Mercury',
    signLord: 'Mars',
    sign: 'Scorpio',
    element: 'Air',
    animal: 'Deer',
    tree: 'Pine',
    bird: 'Brahman Duck',
    guna: 'Sattva',
    motivation: 'Artha',
    gender: 'Female',
    caste: 'Vaishya',
    bodyPart: 'Neck',
    hostileDasas: ['Jupiter', 'Mars', 'Ketu'],
    hostileNakshatras: ['Ashwini', 'Hasta', 'Shravana'],
    characteristics: 'Born in Jyeshtha, your star lord is Mercury. You possess the qualities of seniority, protection, and heroism. You are intellectual and have the ability to overcome enemies. During unfavorable periods, arrogance and vindictiveness may arise.',
    generalAdvice: 'Practice humility and forgiveness during hostile periods. Avoid power struggles and let go of grudges. Channel protective instincts toward community service.',
    remedies: {
      prayer: 'Pray to Lord Indra (King of Gods) and Lord Vishnu. Visit temples on Wednesdays and offer green flowers. Perform charitable activities for protection of the weak.',
      fasting: 'Observe fasting on Wednesdays and on days when Jyeshtha nakshatra falls',
      dress: 'Wear green, emerald, and teal colors to please Mercury. Royal blue also suits the protective nature of this star.',
      deity: 'Indra (King of Gods) is the presiding deity. Worship Lord Ganesha for wisdom and protection.',
      mantras: ['Om Indraaya Namah', 'Om Budhaya Namah'],
      nurturing: 'Caring for deer and feeding Brahmins brings fortune. Protect Pine trees. Air-related activities like pranayama and incense offerings are highly beneficial.',
    },
  },
  'Mula': {
    nakshatra: 'Mula',
    starLord: 'Ketu',
    signLord: 'Jupiter',
    sign: 'Sagittarius',
    element: 'Air',
    animal: 'Dog',
    tree: 'Anjan (Sal Tree)',
    bird: 'Red Vulture',
    guna: 'Tamas',
    motivation: 'Kama',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Feet',
    hostileDasas: ['Mercury', 'Rahu', 'Saturn'],
    hostileNakshatras: ['Bharani', 'Hasta', 'Shravana'],
    characteristics: 'Born in Mula, your star lord is Ketu. You are deeply investigative, spiritual, and have the power of uprooting and renewal. You seek truth at its roots. During unfavorable periods, destructive tendencies and upheavals may occur.',
    generalAdvice: 'Channel your destructive energy into positive transformation during challenging times. Avoid tearing down without building up. Practice spiritual disciplines and seek the root causes rather than symptoms.',
    remedies: {
      prayer: 'Pray to Goddess Nirriti (Alakshmi) and Lord Ganesha for transformation. Visit Kali temples and perform Shanti Puja. Offer dark flowers and sesame seeds.',
      fasting: 'Observe fasting on Tuesdays and on days when Mula nakshatra falls',
      dress: 'Wear brown, earthy tones, and saffron to please Ketu. Avoid very flashy colors during hostile periods.',
      deity: 'Nirriti (Goddess of Dissolution) is the presiding deity. Worship Goddess Kali for transformation.',
      mantras: ['Om Nirritaye Namah', 'Om Ketve Namah'],
      nurturing: 'Caring for dogs brings good fortune. Protect Sal trees and root plants. Air element practices like deep breathing and incense offering are beneficial.',
    },
  },
  'Purva Ashadha': {
    nakshatra: 'Purva Ashadha',
    starLord: 'Venus',
    signLord: 'Jupiter',
    sign: 'Sagittarius',
    element: 'Air',
    animal: 'Monkey',
    tree: 'Ashoka Tree',
    bird: 'Francolin',
    guna: 'Rajas',
    motivation: 'Moksha',
    gender: 'Female',
    caste: 'Brahmin',
    bodyPart: 'Thighs',
    hostileDasas: ['Saturn', 'Rahu', 'Ketu'],
    hostileNakshatras: ['Rohini', 'Punarvasu', 'Anuradha'],
    characteristics: 'Born in Purva Ashadha, your star lord is Venus. You are invincible in spirit, purifying in nature, and achieve early victories. You have a philosophical outlook with artistic sensibilities. During unfavorable periods, overconfidence and pride may lead to setbacks.',
    generalAdvice: 'Maintain humility despite early successes. Prepare thoroughly rather than relying solely on luck during hostile periods. Practice purification rituals and maintain spiritual discipline.',
    remedies: {
      prayer: 'Pray to Water Deities (Apas) and Goddess Lakshmi. Visit temples near water bodies on Fridays. Offer white lotus and perform Abhisheka.',
      fasting: 'Observe fasting on Fridays and on days when Purva Ashadha falls',
      dress: 'Wear white, cream, and light blue to please Venus. Silver and pearl jewelry are auspicious.',
      deity: 'Apas (Water Deity) is the presiding deity. Worship Goddess Saraswati and Lakshmi.',
      mantras: ['Om Adbhyo Namah', 'Om Shukraaya Namah'],
      nurturing: 'Caring for monkeys and aquatic life brings fortune. Plant and protect Ashoka trees. Air and water-related rituals are highly beneficial.',
    },
  },
  'Uttara Ashadha': {
    nakshatra: 'Uttara Ashadha',
    starLord: 'Sun',
    signLord: 'Jupiter/Saturn',
    sign: 'Sagittarius/Capricorn',
    element: 'Air',
    animal: 'Mongoose',
    tree: 'Jackfruit',
    bird: 'Stork',
    guna: 'Sattva',
    motivation: 'Moksha',
    gender: 'Female',
    caste: 'Kshatriya',
    bodyPart: 'Waist',
    hostileDasas: ['Saturn', 'Rahu', 'Mercury'],
    hostileNakshatras: ['Rohini', 'Vishakha', 'Bharani'],
    characteristics: 'Born in Uttara Ashadha, your star lord is Sun. You achieve lasting and final victory through righteous means. You possess leadership qualities, a strong sense of duty, and universal appeal. During unfavorable periods, rigidity and loneliness may affect you.',
    generalAdvice: 'Maintain flexibility and openness during challenging periods. Seek companionship and collaboration rather than going it alone. Continue righteous pursuits regardless of obstacles.',
    remedies: {
      prayer: 'Pray to Vishwadevas (Universal Gods) and Sun God. Offer water to the Sun at sunrise. Visit temples on Sundays and perform community service.',
      fasting: 'Observe fasting on Sundays and on days when Uttara Ashadha falls',
      dress: 'Wear golden, orange, and saffron to honor the Sun. White is also auspicious for this righteous star.',
      deity: 'Vishwadevas (All Gods collectively) are the presiding deities. Worship Lord Vishnu and Surya.',
      mantras: ['Om Vishvadevebhyo Namah', 'Om Suryaaya Namah'],
      nurturing: 'Caring for mongoose and feeding storks brings fortune. Protect Jackfruit trees. Air element practices and sunrise worship are highly beneficial.',
    },
  },
  'Shravana': {
    nakshatra: 'Shravana',
    starLord: 'Moon',
    signLord: 'Saturn',
    sign: 'Capricorn',
    element: 'Air',
    animal: 'Monkey',
    tree: 'Arka (Crown Flower)',
    bird: 'Quail',
    guna: 'Rajas',
    motivation: 'Artha',
    gender: 'Male',
    caste: 'Shudra',
    bodyPart: 'Ears',
    hostileDasas: ['Rahu', 'Mars', 'Ketu'],
    hostileNakshatras: ['Jyeshtha', 'Ashwini', 'Hasta'],
    characteristics: 'Born in Shravana, your star lord is Moon. You are an excellent listener, learner, and communicator. You have the ability to connect people and ideas. During unfavorable periods, hearing problems, misunderstandings, and emotional sensitivity may arise.',
    generalAdvice: 'Practice active listening and clear communication during hostile periods. Avoid spreading unverified information. Maintain emotional balance through meditation and lunar worship.',
    remedies: {
      prayer: 'Pray to Lord Vishnu and perform Vishnu Sahasranama. Visit Vishnu temples on Mondays. Offer tulsi leaves and white flowers.',
      fasting: 'Observe fasting on Mondays and on Ekadashi days',
      dress: 'Wear white, silver, and light blue to please Moon. Pearl jewelry is highly auspicious.',
      deity: 'Lord Vishnu is the presiding deity. Worship Vishnu in any form (Rama, Krishna, Narayana).',
      mantras: ['Om Vishnave Namah', 'Om Chandraaya Namah'],
      nurturing: 'Caring for monkeys and small animals brings fortune. Plant Crown Flower (Arka) plants. Air element practices and listening to sacred music are highly beneficial.',
    },
  },
  'Dhanishta': {
    nakshatra: 'Dhanishta',
    starLord: 'Mars',
    signLord: 'Saturn/Saturn',
    sign: 'Capricorn/Aquarius',
    element: 'Ether',
    animal: 'Lion',
    tree: 'Shami (Prosopis)',
    bird: 'Golden Bee',
    guna: 'Tamas',
    motivation: 'Dharma',
    gender: 'Female',
    caste: 'Vaishya',
    bodyPart: 'Back',
    hostileDasas: ['Saturn', 'Rahu', 'Mercury'],
    hostileNakshatras: ['Ashlesha', 'Magha', 'Chitra'],
    characteristics: 'Born in Dhanishta, your star lord is Mars. You possess wealth-attracting abilities, musical talent, and versatility. You are physically strong and courageous. During unfavorable periods, aggression and marital discord may arise.',
    generalAdvice: 'Channel martial energy into sports, music, or constructive activities during hostile periods. Avoid unnecessary conflicts. Practice patience with family members and partners.',
    remedies: {
      prayer: 'Pray to Eight Vasus (Elemental Gods) and Lord Hanuman. Visit temples on Tuesdays and offer red flowers. Play or listen to drums and percussion instruments.',
      fasting: 'Observe fasting on Tuesdays and on days when Dhanishta nakshatra falls',
      dress: 'Wear red, coral, and bright colors to please Mars. Black also suits the Saturn-ruled sign connection.',
      deity: 'Eight Vasus (Elemental Gods of nature) are the presiding deities. Worship Lord Shiva and Hanuman.',
      mantras: ['Om Vasubhyo Namah', 'Om Mangalaaya Namah'],
      nurturing: 'Feeding lions (at sanctuaries) and protecting wild animals brings fortune. Plant Shami trees. Ether element connection makes music, sound healing, and mantra chanting especially powerful.',
    },
  },
  'Shatabhisha': {
    nakshatra: 'Shatabhisha',
    starLord: 'Rahu',
    signLord: 'Saturn',
    sign: 'Aquarius',
    element: 'Ether',
    animal: 'Horse',
    tree: 'Kadamba',
    bird: 'Raven',
    guna: 'Tamas',
    motivation: 'Dharma',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Jaws, right thigh',
    hostileDasas: ['Sun', 'Mars', 'Ketu'],
    hostileNakshatras: ['Purva Phalguni', 'Ardra', 'Uttara Phalguni'],
    characteristics: 'Born in Shatabhisha (meaning "hundred healers"), your star lord is Rahu. You possess healing abilities, scientific aptitude, and an independent streak. You may be interested in mysticism and alternative medicine. During unfavorable periods, isolation and eccentric behavior may intensify.',
    generalAdvice: 'Maintain social connections during challenging periods. Channel healing abilities into serving others. Avoid isolation and practice group activities. Use technology wisely.',
    remedies: {
      prayer: 'Pray to Lord Varuna (God of Cosmic Waters) and perform Abhisheka. Visit temples near water bodies on Saturdays. Offer dark blue flowers.',
      fasting: 'Observe fasting on Saturdays and on days when Shatabhisha nakshatra falls',
      dress: 'Wear dark blue, electric blue, and black to please Rahu. Hessonite (Gomed) jewelry is auspicious.',
      deity: 'Varuna (God of Cosmic Waters and Cosmic Order) is the presiding deity. Worship Shiva and Hanuman.',
      mantras: ['Om Varunaya Namah', 'Om Rahave Namah'],
      nurturing: 'Caring for horses brings good fortune. Plant Kadamba trees. Ether element connection makes meditation, healing practices, and water rituals especially powerful.',
    },
  },
  'Purva Bhadrapada': {
    nakshatra: 'Purva Bhadrapada',
    starLord: 'Jupiter',
    signLord: 'Saturn/Jupiter',
    sign: 'Aquarius/Pisces',
    element: 'Ether',
    animal: 'Lion',
    tree: 'Mango',
    bird: 'Avocet',
    guna: 'Sattva',
    motivation: 'Artha',
    gender: 'Male',
    caste: 'Brahmin',
    bodyPart: 'Left thigh',
    hostileDasas: ['Mercury', 'Venus', 'Saturn'],
    hostileNakshatras: ['Bharani', 'Pushya', 'Hasta'],
    characteristics: 'Born in Purva Bhadrapada, your star lord is Jupiter. You are intense, transformative, and spiritually inclined with philosophical depth. You have the power to uplift through radical change. During unfavorable periods, extreme behavior and financial instability may surface.',
    generalAdvice: 'Maintain balance between spiritual and material worlds during hostile periods. Avoid extreme positions and practice the middle path. Channel transformative energy through charitable work.',
    remedies: {
      prayer: 'Pray to Aja Ekapada (One-footed Serpent of the Deep) and Lord Shiva. Visit Shiva temples on Thursdays. Perform fire rituals and charitable donations.',
      fasting: 'Observe fasting on Thursdays and on days when Purva Bhadrapada falls',
      dress: 'Wear yellow, golden, and saffron to please Jupiter. Dark blue also suits the Aquarius connection.',
      deity: 'Aja Ekapada (Cosmic Serpent) is the presiding deity. Worship Lord Shiva in Rudra form.',
      mantras: ['Om Aja Ekapaade Namah', 'Om Gurave Namah'],
      nurturing: 'Feeding lions (at sanctuaries) and supporting spiritual institutions brings fortune. Plant and protect Mango trees. Ether element makes deep meditation and philosophical study especially beneficial.',
    },
  },
  'Uttara Bhadrapada': {
    nakshatra: 'Uttara Bhadrapada',
    starLord: 'Saturn',
    signLord: 'Jupiter',
    sign: 'Pisces',
    element: 'Ether',
    animal: 'Cow',
    tree: 'Neem',
    bird: 'Koil (Indian Cuckoo)',
    guna: 'Tamas',
    motivation: 'Kama',
    gender: 'Male',
    caste: 'Kshatriya',
    bodyPart: 'Legs',
    hostileDasas: ['Sun', 'Mars', 'Rahu'],
    hostileNakshatras: ['Bharani', 'Pushya', 'Swati'],
    characteristics: 'Born in Uttara Bhadrapada, your star lord is Saturn. You possess deep wisdom, discipline, and kundalini awareness. You are compassionate and charitable with profound spiritual depth. During unfavorable periods, depression and physical ailments may trouble you.',
    generalAdvice: 'Maintain spiritual practices and charitable work during challenging periods. Avoid excessive solitude. Practice yoga and meditation for kundalini balance. Seek support from spiritual teachers.',
    remedies: {
      prayer: 'Pray to Ahir Budhnya (Serpent of the Deep) and Lord Shiva. Visit Shiva temples on Saturdays. Perform Naga Puja and charitable donations to the poor.',
      fasting: 'Observe fasting on Saturdays and on Ekadashi days',
      dress: 'Wear dark blue, black, and violet to please Saturn. White is also auspicious for the Pisces connection.',
      deity: 'Ahir Budhnya (Serpent of the Cosmic Depths) is the presiding deity. Worship Lord Shiva and Vishnu.',
      mantras: ['Om Ahir Budhnyaaya Namah', 'Om Shanaishcharaya Namah'],
      nurturing: 'Caring for cows and donating to cow shelters brings tremendous fortune. Plant and protect Neem trees. Ether element makes deep meditation and yoga practice especially transformative.',
    },
  },
  'Revati': {
    nakshatra: 'Revati',
    starLord: 'Mercury',
    signLord: 'Jupiter',
    sign: 'Pisces',
    element: 'Ether',
    animal: 'Elephant',
    tree: 'Mahua (Madhuca)',
    bird: 'Kestrel',
    guna: 'Sattva',
    motivation: 'Moksha',
    gender: 'Female',
    caste: 'Shudra',
    bodyPart: 'Ankles, feet',
    hostileDasas: ['Jupiter', 'Mars', 'Ketu'],
    hostileNakshatras: ['Mrigashira', 'Chitra', 'Anuradha'],
    characteristics: 'Born in Revati (the last nakshatra), your star lord is Mercury. You are nurturing, protective, and guide others on their journey. You have a gentle, compassionate nature with artistic sensibilities. During unfavorable periods, gullibility and financial losses may occur.',
    generalAdvice: 'Be cautious in financial dealings during hostile periods. Verify before trusting others completely. Maintain your nurturing nature but set healthy boundaries. Practice discernment.',
    remedies: {
      prayer: 'Pray to Pushan (God of Nourishment and Safe Journeys) and Lord Vishnu. Visit temples on Wednesdays and offer green flowers. Perform charity for travelers and the homeless.',
      fasting: 'Observe fasting on Wednesdays and on days when Revati nakshatra falls',
      dress: 'Wear green, emerald, and light blue to please Mercury. Yellow also suits the Jupiter-ruled Pisces connection.',
      deity: 'Pushan (Nourisher and Protector of Travelers) is the presiding deity. Worship Lord Krishna.',
      mantras: ['Om Pushne Namah', 'Om Budhaya Namah'],
      nurturing: 'Caring for elephants and feeding fish brings good fortune. Protect Mahua trees. Ether element makes spiritual travel, pilgrimage, and deep meditation especially beneficial.',
    },
  },
};

/**
 * Get nakshatra remedies for a given birth nakshatra
 */
export function getNakshatraRemedies(nakshatra: string): NakshatraRemedy | null {
  return nakshatraRemedies[nakshatra] || null;
}
