/**
 * PDF Report Generator
 * Generates a comprehensive Vedic astrology report using jsPDF
 */

import jsPDF from 'jspdf';
import { Planet, DashaWithAntardasha, PlanetAnalysis, YogaResult, DoshaResult, GemstoneRecommendation, TransitPrediction, SadeSatiResult, RashiDetail, NakshatraDetail } from '@/types';
import { signNames } from '@/lib/vedic-constants';

interface ReportData {
  name: string;
  birthDate: string;
  birthTime: string;
  birthPlace: string;
  moonSign: string;
  moonSignHindi: string;
  ascendant: string;
  ascendantHindi: string;
  ascendantSignIndex: number;
  nakshatra: string;
  nakshatraPada: number;
  sunSign: string;
  tithi: string;
  yoga: string;
  karana: string;
  positions: Record<string, Planet>;
  dashas: DashaWithAntardasha[];
  planetAnalysis: PlanetAnalysis[];
  yogas: YogaResult[];
  doshas: DoshaResult[];
  gemstones: GemstoneRecommendation[];
  transits: TransitPrediction[];
  sadeSati: SadeSatiResult;
  rashiData: RashiDetail;
  nakshatraData: NakshatraDetail;
  ascRashiData: RashiDetail;
}

const COLORS = {
  primary: [184, 134, 11] as [number, number, number],    // Dark goldenrod (#B8860B)
  dark: [255, 254, 250] as [number, number, number],      // Warm white bg (#FFFEFA)
  text: [26, 26, 26] as [number, number, number],         // Dark text (#1a1a1a)
  muted: [102, 102, 102] as [number, number, number],     // Muted text (#666)
  accent: [184, 134, 11] as [number, number, number],     // Dark goldenrod (#B8860B)
  green: [22, 133, 64] as [number, number, number],       // Dark green
  red: [200, 30, 30] as [number, number, number],         // Dark red
  yellow: [161, 98, 7] as [number, number, number],       // Dark amber (#A16207)
  white: [26, 26, 26] as [number, number, number],        // Dark text (for name on cover)
  sectionBg: [253, 246, 227] as [number, number, number], // Light golden (#FDF6E3)
};

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

class ReportBuilder {
  private doc: jsPDF;
  private y: number;
  private pageNum: number;

  constructor() {
    this.doc = new jsPDF('p', 'mm', 'a4');
    this.y = MARGIN;
    this.pageNum = 1;
  }

  private checkPageBreak(needed: number = 20) {
    if (this.y + needed > PAGE_HEIGHT - MARGIN) {
      this.addFooter();
      this.doc.addPage();
      this.pageNum++;
      this.y = MARGIN;
      this.addPageBg();
    }
  }

  private addPageBg() {
    this.doc.setFillColor(...COLORS.dark);
    this.doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
  }

  private addFooter() {
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(`Page ${this.pageNum}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
    this.doc.text('Generated by VedicAstro', PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }

  private sectionTitle(title: string) {
    this.checkPageBreak(15);
    this.y += 4;
    this.doc.setFillColor(...COLORS.sectionBg);
    this.doc.roundedRect(MARGIN, this.y - 3, CONTENT_WIDTH, 10, 2, 2, 'F');
    this.doc.setFontSize(12);
    this.doc.setTextColor(...COLORS.accent);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, MARGIN + 4, this.y + 4);
    this.y += 14;
  }

  private label(text: string) {
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(text, MARGIN, this.y);
  }

  private value(text: string, x: number = MARGIN + 40) {
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COLORS.text);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(text, x, this.y);
    this.y += 5;
  }

  private bodyText(text: string, maxWidth: number = CONTENT_WIDTH) {
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COLORS.text);
    this.doc.setFont('helvetica', 'normal');
    const lines = this.doc.splitTextToSize(text, maxWidth);
    this.checkPageBreak(lines.length * 4 + 2);
    this.doc.text(lines, MARGIN, this.y);
    this.y += lines.length * 4 + 2;
  }

  private mutedText(text: string, maxWidth: number = CONTENT_WIDTH) {
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.setFont('helvetica', 'normal');
    const lines = this.doc.splitTextToSize(text, maxWidth);
    this.checkPageBreak(lines.length * 3.5 + 2);
    this.doc.text(lines, MARGIN, this.y);
    this.y += lines.length * 3.5 + 2;
  }

  private row(labelStr: string, valueStr: string) {
    this.checkPageBreak(6);
    this.label(labelStr);
    this.value(valueStr);
  }

  private bulletPoint(text: string) {
    this.checkPageBreak(6);
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text('\u2022', MARGIN + 2, this.y);
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH - 8);
    this.doc.text(lines, MARGIN + 6, this.y);
    this.y += lines.length * 3.5 + 1.5;
  }

  generate(data: ReportData): jsPDF {
    // --- Cover Page ---
    this.addPageBg();

    this.y = 60;
    this.doc.setFontSize(28);
    this.doc.setTextColor(...COLORS.accent);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Vedic Birth Chart', PAGE_WIDTH / 2, this.y, { align: 'center' });

    this.y += 12;
    this.doc.setFontSize(18);
    this.doc.setTextColor(...COLORS.primary);
    this.doc.text('Complete Horoscope Report', PAGE_WIDTH / 2, this.y, { align: 'center' });

    this.y += 20;
    this.doc.setFontSize(22);
    this.doc.setTextColor(...COLORS.white);
    this.doc.text(data.name, PAGE_WIDTH / 2, this.y, { align: 'center' });

    this.y += 15;
    this.doc.setFontSize(11);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(`Born: ${new Date(data.birthDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, PAGE_WIDTH / 2, this.y, { align: 'center' });
    this.y += 6;
    this.doc.text(`Time: ${data.birthTime} | Place: ${data.birthPlace}`, PAGE_WIDTH / 2, this.y, { align: 'center' });

    this.y += 20;
    this.doc.setFontSize(10);
    this.doc.setTextColor(...COLORS.text);
    const summaryItems = [
      `Moon Sign: ${data.moonSign} (${data.moonSignHindi})`,
      `Ascendant: ${data.ascendant} (${data.ascendantHindi})`,
      `Nakshatra: ${data.nakshatra} (Pada ${data.nakshatraPada})`,
      `Sun Sign: ${data.sunSign}`,
    ];
    summaryItems.forEach(item => {
      this.doc.text(item, PAGE_WIDTH / 2, this.y, { align: 'center' });
      this.y += 6;
    });

    this.y += 10;
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, PAGE_WIDTH / 2, this.y, { align: 'center' });

    this.addFooter();

    // --- Page 2: Panchanga + Birth Profile ---
    this.doc.addPage();
    this.pageNum++;
    this.addPageBg();
    this.y = MARGIN;

    this.sectionTitle('1. Birth Profile & Panchanga');
    this.row('Name', data.name);
    this.row('Date of Birth', new Date(data.birthDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
    this.row('Time of Birth', data.birthTime);
    this.row('Place of Birth', data.birthPlace);
    this.y += 3;
    this.row('Moon Sign (Rashi)', `${data.moonSign} (${data.moonSignHindi})`);
    this.row('Ascendant (Lagna)', `${data.ascendant} (${data.ascendantHindi})`);
    this.row('Sun Sign', data.sunSign);
    this.row('Nakshatra', `${data.nakshatra} - Pada ${data.nakshatraPada}`);
    this.row('Tithi', data.tithi);
    this.row('Yoga', data.yoga);
    this.row('Karana', data.karana);
    this.row('Nakshatra Deity', data.nakshatraData.deity);
    this.row('Nakshatra Ruler', data.nakshatraData.ruler);

    // --- Personality ---
    this.sectionTitle('2. Personality & Characteristics');
    this.bodyText(`Moon Sign: ${data.rashiData.name} (${data.rashiData.sanskrit})`);
    this.bodyText(data.rashiData.characteristics);
    if (data.rashiData.classicalDescription) {
      this.mutedText(`Classical Reference: ${data.rashiData.classicalDescription}`);
    }
    this.y += 2;
    this.mutedText(`Strengths: ${data.rashiData.strengths.join(', ')}`);
    this.mutedText(`Challenges: ${data.rashiData.challenges.join(', ')}`);
    this.y += 2;
    this.bodyText(`Nakshatra: ${data.nakshatra}`);
    this.mutedText(data.nakshatraData.qualities);
    this.mutedText(`Suitable Careers: ${data.nakshatraData.careers.join(', ')}`);

    if (data.ascRashiData.name !== data.rashiData.name) {
      this.y += 2;
      this.bodyText(`Ascendant: ${data.ascRashiData.name} (${data.ascRashiData.sanskrit})`);
      this.bodyText(data.ascRashiData.characteristics);
      if (data.ascRashiData.classicalDescription) {
        this.mutedText(`Classical Reference: ${data.ascRashiData.classicalDescription}`);
      }
      this.mutedText(`Strengths: ${data.ascRashiData.strengths.join(', ')}`);
      this.mutedText(`Challenges: ${data.ascRashiData.challenges.join(', ')}`);
    }

    // --- Planet Positions ---
    this.sectionTitle('3. Planetary Positions');

    const planetHeaders = ['Planet', 'Sign', 'Degree', 'House', 'Nakshatra', 'Pada', 'Status'];
    const colWidths = [22, 30, 16, 14, 28, 12, 28];
    let xPos = MARGIN;

    this.doc.setFontSize(8);
    this.doc.setTextColor(...COLORS.accent);
    this.doc.setFont('helvetica', 'bold');
    planetHeaders.forEach((h, i) => {
      this.doc.text(h, xPos, this.y);
      xPos += colWidths[i];
    });
    this.y += 2;
    this.doc.setDrawColor(...COLORS.primary);
    this.doc.line(MARGIN, this.y, MARGIN + CONTENT_WIDTH, this.y);
    this.y += 4;

    const planetOrder = ['Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter', 'Venus', 'Saturn', 'Rahu', 'Ketu'];
    this.doc.setFont('helvetica', 'normal');

    for (const pName of planetOrder) {
      const p = data.positions[pName];
      if (!p) continue;
      this.checkPageBreak(6);
      xPos = MARGIN;
      const analysis = data.planetAnalysis.find(a => a.planet === pName);
      const statusText = analysis?.isMostMalefic ? 'Most Malefic' : analysis?.isBenefic ? 'Benefic' : 'Neutral';

      this.doc.setFontSize(8);
      this.doc.setTextColor(...COLORS.text);
      this.doc.text(`${pName}${p.retrograde ? ' (R)' : ''}`, xPos, this.y); xPos += colWidths[0];
      this.doc.text(`${p.sign}`, xPos, this.y); xPos += colWidths[1];
      this.doc.text(`${p.degree}`, xPos, this.y); xPos += colWidths[2];
      this.doc.text(`${p.house}`, xPos, this.y); xPos += colWidths[3];
      this.doc.text(`${p.nakshatra}`, xPos, this.y); xPos += colWidths[4];
      this.doc.text(`${p.nakshatraPada}`, xPos, this.y); xPos += colWidths[5];

      if (analysis?.isMostMalefic) this.doc.setTextColor(...COLORS.red);
      else if (analysis?.isBenefic) this.doc.setTextColor(...COLORS.green);
      else this.doc.setTextColor(...COLORS.yellow);
      this.doc.text(statusText, xPos, this.y);

      this.y += 5;
    }

    // --- Planet Analysis ---
    this.sectionTitle('4. Planet Analysis');
    for (const a of data.planetAnalysis) {
      this.checkPageBreak(12);
      this.doc.setFontSize(9);
      this.doc.setTextColor(a.isMostMalefic ? COLORS.red[0] : a.isBenefic ? COLORS.green[0] : COLORS.yellow[0],
                             a.isMostMalefic ? COLORS.red[1] : a.isBenefic ? COLORS.green[1] : COLORS.yellow[1],
                             a.isMostMalefic ? COLORS.red[2] : a.isBenefic ? COLORS.green[2] : COLORS.yellow[2]);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${a.planet} — ${a.sign}, House ${a.house}`, MARGIN, this.y);
      this.y += 4;
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      const lines = this.doc.splitTextToSize(a.interpretation, CONTENT_WIDTH);
      this.doc.setFontSize(8);
      this.doc.text(lines, MARGIN, this.y);
      this.y += lines.length * 3.5 + 3;
    }

    // --- Houses ---
    this.sectionTitle('5. House (Bhava) Predictions');
    for (let h = 1; h <= 12; h++) {
      this.checkPageBreak(14);
      const houseSignIndex = (data.ascendantSignIndex + h - 1) % 12;
      const planetsInHouse = planetOrder.filter(p => data.positions[p]?.house === h);

      this.doc.setFontSize(9);
      this.doc.setTextColor(...COLORS.primary);
      this.doc.setFont('helvetica', 'bold');
      const houseNames: Record<number, string> = { 1: 'Lagna', 2: 'Dhana', 3: 'Sahaja', 4: 'Sukha', 5: 'Putra', 6: 'Ripu', 7: 'Kalatra', 8: 'Ayu', 9: 'Dharma', 10: 'Karma', 11: 'Labha', 12: 'Vyaya' };
      this.doc.text(`House ${h} (${houseNames[h]}) — ${signNames[houseSignIndex]}`, MARGIN, this.y);
      this.y += 4;

      if (planetsInHouse.length > 0) {
        this.doc.setFontSize(8);
        this.doc.setTextColor(...COLORS.accent);
        this.doc.text(`Planets: ${planetsInHouse.join(', ')}`, MARGIN + 4, this.y);
        this.y += 4;
      }
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.setFontSize(8);
      // Use houseSignifications data if available
      const houseKeywords = data.planetAnalysis.find(a => a.house === h)?.houseKeywords;
      if (houseKeywords && houseKeywords.length) {
        this.doc.text(`Keywords: ${houseKeywords.join(', ')}`, MARGIN + 4, this.y);
        this.y += 4;
      }
      this.y += 2;
    }

    // --- Dasha ---
    this.sectionTitle('6. Vimshottari Dasha Timeline');
    for (const d of data.dashas) {
      this.checkPageBreak(18);
      const ratingColors: Record<string, [number, number, number]> = {
        excellent: COLORS.green,
        favourable: [37, 99, 195],
        mixed: COLORS.yellow,
        challenging: COLORS.red,
      };
      const color = ratingColors[d.rating] || COLORS.text;

      this.doc.setFontSize(10);
      this.doc.setTextColor(color[0], color[1], color[2]);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${d.planet} Mahadasha (${d.startYear}–${d.endYear})`, MARGIN, this.y);
      this.doc.setFontSize(8);
      this.doc.text(`[${d.rating.toUpperCase()}]`, MARGIN + 80, this.y);
      if (d.isCurrent) {
        this.doc.setTextColor(...COLORS.accent);
        this.doc.text('CURRENT', MARGIN + CONTENT_WIDTH - 20, this.y);
      }
      this.y += 4;
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      const reasonLines = this.doc.splitTextToSize(d.ratingReason, CONTENT_WIDTH - 4);
      this.doc.text(reasonLines, MARGIN + 2, this.y);
      this.y += reasonLines.length * 3.5 + 3;
    }

    // --- Yogas ---
    this.sectionTitle('7. Planetary Yogas');
    if (data.yogas.length === 0) {
      this.mutedText('No major yogas identified in this chart configuration.');
    } else {
      for (const y of data.yogas) {
        this.checkPageBreak(16);
        this.doc.setFontSize(10);
        this.doc.setTextColor(...COLORS.accent);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(`${y.name} [${y.strength}]`, MARGIN, this.y);
        this.y += 4;
        this.doc.setFont('helvetica', 'normal');
        this.doc.setFontSize(8);
        this.doc.setTextColor(...COLORS.text);
        const descLines = this.doc.splitTextToSize(y.description, CONTENT_WIDTH - 4);
        this.doc.text(descLines, MARGIN + 2, this.y);
        this.y += descLines.length * 3.5 + 1;
        this.doc.setTextColor(...COLORS.muted);
        const effectLines = this.doc.splitTextToSize(y.effects, CONTENT_WIDTH - 4);
        this.doc.text(effectLines, MARGIN + 2, this.y);
        this.y += effectLines.length * 3.5 + 1;
        this.doc.text(`Planets: ${y.planets.join(', ')}`, MARGIN + 2, this.y);
        this.y += 5;
      }
    }

    // --- Doshas ---
    this.sectionTitle('8. Dosha Analysis');
    for (const d of data.doshas) {
      this.checkPageBreak(20);
      this.doc.setFontSize(10);
      this.doc.setTextColor(d.detected ? COLORS.red[0] : COLORS.green[0], d.detected ? COLORS.red[1] : COLORS.green[1], d.detected ? COLORS.red[2] : COLORS.green[2]);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${d.name} — ${d.detected ? d.severity?.toUpperCase() : 'NOT PRESENT'}`, MARGIN, this.y);
      this.y += 4;
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      this.doc.setFontSize(8);
      const descLines = this.doc.splitTextToSize(d.description, CONTENT_WIDTH - 4);
      this.doc.text(descLines, MARGIN + 2, this.y);
      this.y += descLines.length * 3.5 + 1;

      if (d.detected && d.remedies.length > 0) {
        this.doc.setTextColor(...COLORS.muted);
        this.doc.text('Remedies:', MARGIN + 2, this.y);
        this.y += 4;
        for (const r of d.remedies) {
          this.bulletPoint(r);
        }
      }
      this.y += 2;
    }

    // Sade Sati
    this.checkPageBreak(15);
    this.doc.setFontSize(10);
    this.doc.setTextColor(data.sadeSati.active ? COLORS.red[0] : COLORS.green[0], data.sadeSati.active ? COLORS.red[1] : COLORS.green[1], data.sadeSati.active ? COLORS.red[2] : COLORS.green[2]);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(`Sade Sati — ${data.sadeSati.active ? `ACTIVE (${data.sadeSati.phase} phase)` : 'NOT ACTIVE'}`, MARGIN, this.y);
    this.y += 4;
    this.doc.setFont('helvetica', 'normal');
    this.mutedText(data.sadeSati.description);
    if (data.sadeSati.remedies.length > 0) {
      for (const r of data.sadeSati.remedies) {
        this.bulletPoint(r);
      }
    }

    // --- Gemstones ---
    this.sectionTitle('9. Gemstone Recommendations');
    for (const g of data.gemstones) {
      this.checkPageBreak(25);
      this.doc.setFontSize(10);
      this.doc.setTextColor(...COLORS.accent);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${g.primaryGem} (for ${g.planet})`, MARGIN, this.y);
      this.y += 4;
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(8);
      this.doc.setTextColor(...COLORS.text);
      const reasonLines = this.doc.splitTextToSize(g.reason, CONTENT_WIDTH - 4);
      this.doc.text(reasonLines, MARGIN + 2, this.y);
      this.y += reasonLines.length * 3.5 + 2;

      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(`Weight: ${g.weight} | Metal: ${g.metal} | Finger: ${g.finger}`, MARGIN + 2, this.y);
      this.y += 4;
      this.doc.text(`Starting Day: ${g.startingDay}`, MARGIN + 2, this.y);
      this.y += 4;
      this.doc.text(`Alternative: ${g.alternativeGem}`, MARGIN + 2, this.y);
      this.y += 4;
      this.doc.text(`Mantra: ${g.mantra}`, MARGIN + 2, this.y);
      this.y += 5;
    }

    // --- Transits ---
    this.sectionTitle('10. Current Transit Effects');
    for (const t of data.transits) {
      this.checkPageBreak(10);
      this.doc.setFontSize(9);
      this.doc.setTextColor(t.isPositive ? COLORS.green[0] : COLORS.yellow[0], t.isPositive ? COLORS.green[1] : COLORS.yellow[1], t.isPositive ? COLORS.green[2] : COLORS.yellow[2]);
      this.doc.setFont('helvetica', 'bold');
      this.doc.text(`${t.planet} in ${t.transitSign} (${t.houseFromMoon}th from Moon) — ${t.isPositive ? 'Favourable' : 'Challenging'}`, MARGIN, this.y);
      this.y += 4;
      this.doc.setFont('helvetica', 'normal');
      this.mutedText(t.effects);
    }

    // --- Lucky Elements ---
    this.sectionTitle('11. Lucky Elements & Mantras');
    this.row('Lucky Numbers', data.rashiData.luckyNumbers.join(', '));
    this.row('Lucky Colors', data.rashiData.luckyColors.join(', '));
    this.row('Lucky Days', data.rashiData.luckyDays.join(', '));
    this.row('Direction', data.rashiData.direction);
    this.row('Gemstone', data.rashiData.gem);
    this.row('Deity', data.rashiData.deity);
    this.y += 3;
    this.row('Rashi Mantra', data.rashiData.mantra);
    this.row('Nakshatra Mantra', data.nakshatraData.mantra);

    // Final footer
    this.addFooter();

    return this.doc;
  }
}

export function generateKundliReport(data: ReportData): void {
  const builder = new ReportBuilder();
  const doc = builder.generate(data);
  doc.save(`${data.name.replace(/\s+/g, '_')}_Vedic_Horoscope.pdf`);
}

export type { ReportData };
