import { ZodiacSign, ZodiacWheelSign } from '@/types';

export const zodiacData: Record<string, ZodiacSign> = {
  aries: {
    key: 'aries',
    name: 'Mesha (Aries)',
    symbol: '♈',
    element: 'Fire',
    ruler: 'Mars (Mangal)',
    quality: 'Cardinal',
    dates: 'April 14 - May 14',
    lucky_numbers: '1, 8, 17',
    lucky_colors: 'Red, Scarlet',
    lucky_day: 'Tuesday',
    compatible: 'Leo, Sagittarius',
    description: 'Aries natives are natural leaders with boundless energy and enthusiasm. Ruled by Mars, they are courageous, confident, and always ready to take initiative.'
  },
  taurus: {
    key: 'taurus',
    name: 'Vrishabha (Taurus)',
    symbol: '♉',
    element: 'Earth',
    ruler: 'Venus (Shukra)',
    quality: 'Fixed',
    dates: 'May 15 - June 14',
    lucky_numbers: '2, 6, 9',
    lucky_colors: 'Green, Pink',
    lucky_day: 'Friday',
    compatible: 'Virgo, Capricorn',
    description: 'Taurus natives are grounded, practical, and value stability. Ruled by Venus, they appreciate beauty, comfort, and the finer things in life.'
  },
  gemini: {
    key: 'gemini',
    name: 'Mithuna (Gemini)',
    symbol: '♊',
    element: 'Air',
    ruler: 'Mercury (Budha)',
    quality: 'Mutable',
    dates: 'June 15 - July 14',
    lucky_numbers: '3, 5, 7',
    lucky_colors: 'Yellow, Green',
    lucky_day: 'Wednesday',
    compatible: 'Libra, Aquarius',
    description: 'Gemini natives are intellectually curious, versatile, and excellent communicators. Ruled by Mercury, they thrive on mental stimulation and variety.'
  },
  cancer: {
    key: 'cancer',
    name: 'Karka (Cancer)',
    symbol: '♋',
    element: 'Water',
    ruler: 'Moon (Chandra)',
    quality: 'Cardinal',
    dates: 'July 15 - August 14',
    lucky_numbers: '2, 7, 11',
    lucky_colors: 'White, Silver',
    lucky_day: 'Monday',
    compatible: 'Scorpio, Pisces',
    description: 'Cancer natives are nurturing, intuitive, and deeply emotional. Ruled by the Moon, they are protective of loved ones and value home and family.'
  },
  leo: {
    key: 'leo',
    name: 'Simha (Leo)',
    symbol: '♌',
    element: 'Fire',
    ruler: 'Sun (Surya)',
    quality: 'Fixed',
    dates: 'August 15 - September 15',
    lucky_numbers: '1, 4, 10',
    lucky_colors: 'Gold, Orange',
    lucky_day: 'Sunday',
    compatible: 'Aries, Sagittarius',
    description: 'Leo natives are confident, charismatic, and natural performers. Ruled by the Sun, they possess strong leadership qualities and creative talents.'
  },
  virgo: {
    key: 'virgo',
    name: 'Kanya (Virgo)',
    symbol: '♍',
    element: 'Earth',
    ruler: 'Mercury (Budha)',
    quality: 'Mutable',
    dates: 'September 16 - October 15',
    lucky_numbers: '5, 14, 23',
    lucky_colors: 'Green, Brown',
    lucky_day: 'Wednesday',
    compatible: 'Taurus, Capricorn',
    description: 'Virgo natives are analytical, detail-oriented, and service-minded. Ruled by Mercury, they excel at organization and problem-solving.'
  },
  libra: {
    key: 'libra',
    name: 'Tula (Libra)',
    symbol: '♎',
    element: 'Air',
    ruler: 'Venus (Shukra)',
    quality: 'Cardinal',
    dates: 'October 16 - November 14',
    lucky_numbers: '6, 15, 24',
    lucky_colors: 'Blue, Pink',
    lucky_day: 'Friday',
    compatible: 'Gemini, Aquarius',
    description: 'Libra natives are diplomatic, fair-minded, and seek harmony. Ruled by Venus, they value relationships and have a refined aesthetic sense.'
  },
  scorpio: {
    key: 'scorpio',
    name: 'Vrishchika (Scorpio)',
    symbol: '♏',
    element: 'Water',
    ruler: 'Mars (Mangal)',
    quality: 'Fixed',
    dates: 'November 15 - December 14',
    lucky_numbers: '9, 18, 27',
    lucky_colors: 'Red, Black',
    lucky_day: 'Tuesday',
    compatible: 'Cancer, Pisces',
    description: 'Scorpio natives are intense, passionate, and deeply perceptive. Ruled by Mars, they possess strong willpower and transformative abilities.'
  },
  sagittarius: {
    key: 'sagittarius',
    name: 'Dhanu (Sagittarius)',
    symbol: '♐',
    element: 'Fire',
    ruler: 'Jupiter (Guru)',
    quality: 'Mutable',
    dates: 'December 15 - January 13',
    lucky_numbers: '3, 12, 21',
    lucky_colors: 'Yellow, Purple',
    lucky_day: 'Thursday',
    compatible: 'Aries, Leo',
    description: 'Sagittarius natives are optimistic, adventurous, and philosophical. Ruled by Jupiter, they seek truth, wisdom, and new experiences.'
  },
  capricorn: {
    key: 'capricorn',
    name: 'Makara (Capricorn)',
    symbol: '♑',
    element: 'Earth',
    ruler: 'Saturn (Shani)',
    quality: 'Cardinal',
    dates: 'January 14 - February 12',
    lucky_numbers: '8, 17, 26',
    lucky_colors: 'Brown, Black',
    lucky_day: 'Saturday',
    compatible: 'Taurus, Virgo',
    description: 'Capricorn natives are ambitious, disciplined, and practical. Ruled by Saturn, they are patient and work steadily toward their goals.'
  },
  aquarius: {
    key: 'aquarius',
    name: 'Kumbha (Aquarius)',
    symbol: '♒',
    element: 'Air',
    ruler: 'Saturn (Shani)',
    quality: 'Fixed',
    dates: 'February 13 - March 13',
    lucky_numbers: '4, 13, 22',
    lucky_colors: 'Blue, Electric Blue',
    lucky_day: 'Saturday',
    compatible: 'Gemini, Libra',
    description: 'Aquarius natives are innovative, humanitarian, and independent thinkers. Ruled by Saturn, they value freedom and progressive ideas.'
  },
  pisces: {
    key: 'pisces',
    name: 'Meena (Pisces)',
    symbol: '♓',
    element: 'Water',
    ruler: 'Jupiter (Guru)',
    quality: 'Mutable',
    dates: 'March 14 - April 13',
    lucky_numbers: '3, 7, 12',
    lucky_colors: 'Sea Green, Lavender',
    lucky_day: 'Thursday',
    compatible: 'Cancer, Scorpio',
    description: 'Pisces natives are compassionate, intuitive, and artistic. Ruled by Jupiter, they possess deep spiritual sensitivity and creative imagination.'
  }
};

export const zodiacWheelSigns: ZodiacWheelSign[] = [
  { key: 'aries', symbol: '♈', hindi: 'मेष', english: 'Aries' },
  { key: 'taurus', symbol: '♉', hindi: 'वृषभ', english: 'Taurus' },
  { key: 'gemini', symbol: '♊', hindi: 'मिथुन', english: 'Gemini' },
  { key: 'cancer', symbol: '♋', hindi: 'कर्क', english: 'Cancer' },
  { key: 'leo', symbol: '♌', hindi: 'सिंह', english: 'Leo' },
  { key: 'virgo', symbol: '♍', hindi: 'कन्या', english: 'Virgo' },
  { key: 'libra', symbol: '♎', hindi: 'तुला', english: 'Libra' },
  { key: 'scorpio', symbol: '♏', hindi: 'वृश्चिक', english: 'Scorpio' },
  { key: 'sagittarius', symbol: '♐', hindi: 'धनु', english: 'Sagittarius' },
  { key: 'capricorn', symbol: '♑', hindi: 'मकर', english: 'Capricorn' },
  { key: 'aquarius', symbol: '♒', hindi: 'कुम्भ', english: 'Aquarius' },
  { key: 'pisces', symbol: '♓', hindi: 'मीन', english: 'Pisces' }
];

export const signKeys = Object.keys(zodiacData);
